# Generated by Django 2.2.4 on 2019-08-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=10)),
                ('identifier', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publishedDate', models.CharField(max_length=15)),
                ('pageCount', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=20)),
                ('smallThumbnail', models.URLField()),
                ('thumbnail', models.URLField()),
                ('authors', models.ManyToManyField(to='books.Author')),
                ('industryIdentifiers', models.ManyToManyField(to='books.IndustryIdentifier')),
            ],
        ),
    ]
